/**
 * Tiny build script — no bundler needed.
 * Concatenates the source files in dependency order into a single,
 * self-contained dist/tts-widget.js that a website owner can host
 * on their own server with zero other dependencies.
 */
const fs = require("fs");
const path = require("path");

const SRC_DIR = path.join(__dirname, "src");
const DIST_FILE = path.join(__dirname, "dist", "tts-widget.js");
const TEMPLATE_FILE = path.join(__dirname, "configurator", "widget-template.js");

// Order matters: config -> speech -> article-detector -> widget (uses the rest).
const FILES = ["config.js", "speech.js", "article-detector.js", "widget.js"];

function build() {
  const banner = `/*!\n * TTS Widget — bundled build\n * Generated by build.js — do not edit this file directly, edit /src instead.\n */\n(function () {\n"use strict";\n`;
  const footer = `\n})();\n`;

  const body = FILES.map((file) => {
    const filePath = path.join(SRC_DIR, file);
    return `\n/* ---- src/${file} ---- */\n` + fs.readFileSync(filePath, "utf8");
  }).join("\n");

  const bundle = banner + body + footer;

  fs.mkdirSync(path.dirname(DIST_FILE), { recursive: true });
  fs.writeFileSync(DIST_FILE, bundle, "utf8");
  console.log(`Built ${path.relative(__dirname, DIST_FILE)} (${(bundle.length / 1024).toFixed(1)} KB)`);

  // Also expose the bundle as a JS string constant the configurator page
  // can read in-browser (no fetch/network call — avoids CORS issues when
  // the page is just double-clicked open from disk). The "Download" button
  // swaps the default color/radius inside this string before saving it.
  const templateJs =
    `/*!\n * Auto-generated by build.js — do not edit directly, run "node build.js" instead.\n */\n` +
    `window.WIDGET_TEMPLATE = ${JSON.stringify(bundle)};\n`;

  fs.mkdirSync(path.dirname(TEMPLATE_FILE), { recursive: true });
  fs.writeFileSync(TEMPLATE_FILE, templateJs, "utf8");
  console.log(`Built ${path.relative(__dirname, TEMPLATE_FILE)}`);
}

build();
