/**
 * Configurator page logic.
 * - Keeps the color/radius controls, CSS variables, and live preview in sync.
 * - The live preview's Play button uses the REAL speech engine (src/speech.js)
 *   on a short sample sentence — so visitors hear exactly what they'll get.
 * - Download bakes the chosen color/radius into WIDGET_TEMPLATE (generated by
 *   build.js) and saves it as a plain tts-widget.js file — no server involved.
 */
(function () {
  "use strict";

  const colorPicker = document.getElementById("colorPicker");
  const hexInput = document.getElementById("hexInput");
  const colorVal = document.getElementById("colorVal");
  const radiusSlider = document.getElementById("radiusSlider");
  const radiusVal = document.getElementById("radiusVal");
  const liveBar = document.getElementById("liveBar");
  const liveBtn = document.getElementById("liveBtn");
  const liveCaption = document.getElementById("liveCaption");
  const downloadBtn = document.getElementById("downloadBtn");
  const copyBtn = document.getElementById("copyBtn");
  const snippetText = document.getElementById("snippetText");

  let state = { color: "#2563EB", radius: 12 };

  function isValidHex(hex) {
    return /^#([0-9A-Fa-f]{6})$/.test(hex);
  }

  function applyPreviewStyle() {
    liveBar.style.borderRadius = state.radius + "px";
    liveBtn.style.background = state.color;
    liveBtn.style.borderRadius = Math.max(0, state.radius - 4) + "px";
    colorVal.textContent = state.color.toUpperCase();
    radiusVal.textContent = state.radius + "px";
  }

  function setColor(hex) {
    if (!isValidHex(hex)) return;
    state.color = hex;
    colorPicker.value = hex;
    hexInput.value = hex.toUpperCase();
    applyPreviewStyle();
  }

  colorPicker.addEventListener("input", (e) => setColor(e.target.value));
  hexInput.addEventListener("input", (e) => {
    let v = e.target.value.trim();
    if (v && v[0] !== "#") v = "#" + v;
    if (isValidHex(v)) setColor(v);
  });
  document.querySelectorAll(".swatch").forEach((sw) => {
    sw.addEventListener("click", () => setColor(sw.dataset.color));
  });

  radiusSlider.addEventListener("input", (e) => {
    state.radius = parseInt(e.target.value, 10);
    applyPreviewStyle();
  });

  applyPreviewStyle();

  // ---- Live preview playback (real Web Speech API, same engine as the widget) ----
  const speech = new window.TTSSpeechController();
  const SAMPLE_WORDS =
    "This is what your visitors will hear when they click play. Your article will be read aloud in this same natural voice.".split(/\s+/);
  let sampleWordIndex = 0;
  let sampleBaseWordIndex = 0; // words already spoken before the current speech segment started

  speech.onStateChange = (s) => {
    liveBtn.textContent = s === "playing" ? "❚❚" : "▶";
  };
  speech.onWordBoundary = (wordIndex) => {
    // wordIndex is relative to whatever text segment is currently being
    // spoken (which may just be the remaining tail after a resume), so it
    // needs the base offset to represent true position in the sample.
    sampleWordIndex = sampleBaseWordIndex + wordIndex;
    liveCaption.textContent = "Reading…";
  };
  speech.onEnd = () => {
    sampleWordIndex = 0;
    sampleBaseWordIndex = 0;
    liveCaption.textContent = "Press play to hear a sample";
  };

  // Speaks the sample starting at a given word. The Web Speech API has no
  // reliable native pause/resume (Chrome in particular silently breaks it),
  // so "resume" here really means "stop, then re-speak from here" — same
  // approach the actual widget uses.
  function playSampleFromWord(wordIndex) {
    sampleBaseWordIndex = wordIndex;
    sampleWordIndex = wordIndex;
    const remaining = SAMPLE_WORDS.slice(wordIndex).join(" ");
    if (remaining) speech.play(remaining);
  }

  liveBtn.addEventListener("click", () => {
    if (speech.state === "playing") {
      speech.pause();
    } else if (speech.state === "paused") {
      playSampleFromWord(sampleWordIndex);
    } else {
      speech.autoSelectFemaleVoice(navigator.language);
      playSampleFromWord(0);
    }
  });

  // ---- Download: bake current color/radius into the widget bundle ----
  function buildCustomizedWidget() {
    let code = window.WIDGET_TEMPLATE || "";
    code = code.replace(/color:\s*"#[0-9A-Fa-f]{3,8}"/, `color: "${state.color}"`);
    code = code.replace(/borderRadius:\s*"\d+px"/, `borderRadius: "${state.radius}px"`);
    return code;
  }

  downloadBtn.addEventListener("click", () => {
    const code = buildCustomizedWidget();
    const blob = new Blob([code], { type: "text/javascript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "tts-widget.js";
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  });

  copyBtn.addEventListener("click", async () => {
    const text = snippetText.textContent;
    try {
      await navigator.clipboard.writeText(text);
    } catch (e) {
      // Clipboard API can fail on file:// pages in some browsers — fall back silently.
    }
    copyBtn.textContent = "Copied!";
    setTimeout(() => (copyBtn.textContent = "Copy"), 1500);
  });
})();
